{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "b5f1380e-d64d-4bf3-9444-39f661d1ed48",
   "metadata": {},
   "source": [
    "# Evidently Dashboard Prep"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "05990e51-4bcd-4c90-9e75-5718fe57b66a",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of pandas.compat failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/compat/__init__.py\", line 15, in <module>\n",
      "    from pandas.compat.numpy import (\n",
      "ImportError: cannot import name 'is_numpy_dev' from 'pandas.compat.numpy' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py)\n",
      "]\n",
      "[autoreload of pandas._config.config failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 317, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 280, in update_instances\n",
      "    ref.__class__ = new\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/_config/config.py\", line 208, in __setattr__\n",
      "    raise OptionError(\"You can only set the value of existing options\")\n",
      "pandas._config.config.OptionError: 'You can only set the value of existing options'\n",
      "]\n",
      "[autoreload of pandas.core.dtypes.base failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/dtypes/base.py\", line 15, in <module>\n",
      "    from pandas._libs.hashtable import object_hash\n",
      "ImportError: cannot import name 'object_hash' from 'pandas._libs.hashtable' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/_libs/hashtable.cpython-38-x86_64-linux-gnu.so)\n",
      "]\n",
      "[autoreload of pandas.core.dtypes.common failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/dtypes/common.py\", line 26, in <module>\n",
      "    from pandas.core.dtypes.base import _registry as registry\n",
      "ImportError: cannot import name '_registry' from 'pandas.core.dtypes.base' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/dtypes/base.py)\n",
      "]\n",
      "[autoreload of pandas.core.dtypes.cast failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/dtypes/cast.py\", line 43, in <module>\n",
      "    from pandas.util._exceptions import find_stack_level\n",
      "ImportError: cannot import name 'find_stack_level' from 'pandas.util._exceptions' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/util/_exceptions.py)\n",
      "]\n",
      "[autoreload of pandas.core.common failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/common.py\", line 36, in <module>\n",
      "    from pandas.compat import np_version_under1p18\n",
      "ImportError: cannot import name 'np_version_under1p18' from 'pandas.compat' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/compat/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.core.construction failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/construction.py\", line 29, in <module>\n",
      "    from pandas.core.dtypes.base import (\n",
      "ImportError: cannot import name '_registry' from 'pandas.core.dtypes.base' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/dtypes/base.py)\n",
      "]\n",
      "[autoreload of pandas.core.algorithms failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/algorithms.py\", line 34, in <module>\n",
      "    from pandas.core.dtypes.cast import (\n",
      "ImportError: cannot import name 'sanitize_to_nanoseconds' from 'pandas.core.dtypes.cast' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/dtypes/cast.py)\n",
      "]\n",
      "[autoreload of pandas.core.ops.array_ops failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/ops/array_ops.py\", line 48, in <module>\n",
      "    import pandas.core.computation.expressions as expressions\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py\", line 19, in <module>\n",
      "    from pandas.core.computation.check import NUMEXPR_INSTALLED\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/computation/check.py\", line 3, in <module>\n",
      "    ne = import_optional_dependency(\"numexpr\", errors=\"warn\")\n",
      "TypeError: import_optional_dependency() got an unexpected keyword argument 'errors'\n",
      "]\n",
      "[autoreload of pandas.core.ops failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/ops/__init__.py\", line 32, in <module>\n",
      "    from pandas.core.ops.array_ops import (  # noqa:F401\n",
      "ImportError: cannot import name 'maybe_prepare_scalar_for_op' from 'pandas.core.ops.array_ops' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/ops/array_ops.py)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.base failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/arrays/base.py\", line 64, in <module>\n",
      "    from pandas.core.algorithms import (\n",
      "ImportError: cannot import name 'factorize_array' from 'pandas.core.algorithms' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/algorithms.py)\n",
      "]\n",
      "[autoreload of pandas.core.nanops failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/nanops.py\", line 33, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'get_dtype' from 'pandas.core.dtypes.common' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.masked failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/arrays/masked.py\", line 50, in <module>\n",
      "    from pandas.core.algorithms import (\n",
      "ImportError: cannot import name 'factorize_array' from 'pandas.core.algorithms' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/algorithms.py)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.boolean failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: astype() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of pandas.core.accessor failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __dir__() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of pandas.core.arrays.categorical failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/arrays/categorical.py\", line 47, in <module>\n",
      "    from pandas.util._exceptions import find_stack_level\n",
      "ImportError: cannot import name 'find_stack_level' from 'pandas.util._exceptions' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/util/_exceptions.py)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.datetimelike failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/arrays/datetimelike.py\", line 39, in <module>\n",
      "    from pandas._libs.tslibs.fields import (\n",
      "ImportError: cannot import name 'RoundTo' from 'pandas._libs.tslibs.fields' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/_libs/tslibs/fields.cpython-38-x86_64-linux-gnu.so)\n",
      "]\n",
      "[autoreload of pandas.core.arrays._ranges failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/arrays/_ranges.py\", line 9, in <module>\n",
      "    from pandas._libs.lib import i8max\n",
      "ImportError: cannot import name 'i8max' from 'pandas._libs.lib' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/_libs/lib.cpython-38-x86_64-linux-gnu.so)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.datetimes failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py\", line 42, in <module>\n",
      "    from pandas.core.dtypes.cast import astype_dt64_to_dt64tz\n",
      "ImportError: cannot import name 'astype_dt64_to_dt64tz' from 'pandas.core.dtypes.cast' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/dtypes/cast.py)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.integer failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: astype() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of pandas.core.arrays.sparse.array failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/arrays/sparse/array.py\", line 35, in <module>\n",
      "    from pandas.core.dtypes.cast import (\n",
      "ImportError: cannot import name 'maybe_box_datetimelike' from 'pandas.core.dtypes.cast' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/dtypes/cast.py)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.sparse failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/arrays/sparse/__init__.py\", line 7, in <module>\n",
      "    from pandas.core.arrays.sparse.array import (\n",
      "ImportError: cannot import name 'make_sparse_index' from 'pandas.core.arrays.sparse.array' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/arrays/sparse/array.py)\n",
      "]\n",
      "[autoreload of pandas.core.dtypes.concat failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/dtypes/concat.py\", line 27, in <module>\n",
      "    from pandas.core.construction import (\n",
      "ImportError: cannot import name 'ensure_wrapped_if_datetimelike' from 'pandas.core.construction' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/construction.py)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.base failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py\", line 60, in <module>\n",
      "    from pandas.core.dtypes.cast import (\n",
      "ImportError: cannot import name 'can_hold_element' from 'pandas.core.dtypes.cast' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/dtypes/cast.py)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.interval failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/arrays/interval.py\", line 20, in <module>\n",
      "    from pandas._libs.interval import (\n",
      "ImportError: cannot import name 'VALID_CLOSED' from 'pandas._libs.interval' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/_libs/interval.cpython-38-x86_64-linux-gnu.so)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.numpy_ failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/arrays/numpy_.py\", line 26, in <module>\n",
      "    from pandas.core.construction import ensure_wrapped_if_datetimelike\n",
      "ImportError: cannot import name 'ensure_wrapped_if_datetimelike' from 'pandas.core.construction' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/construction.py)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.period failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/arrays/period.py\", line 95, in <module>\n",
      "    class PeriodArray(dtl.DatelikeOps):\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/arrays/period.py\", line 609, in PeriodArray\n",
      "    @dtl.ravel_compat\n",
      "AttributeError: module 'pandas.core.arrays.datetimelike' has no attribute 'ravel_compat'\n",
      "]\n",
      "[autoreload of pandas.core.arrays.string_ failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/arrays/string_.py\", line 22, in <module>\n",
      "    from pandas.compat import pa_version_under1p0\n",
      "ImportError: cannot import name 'pa_version_under1p0' from 'pandas.compat' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/compat/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.timedeltas failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/arrays/timedeltas.py\", line 40, in <module>\n",
      "    from pandas.core.dtypes.cast import astype_td64_unit_conversion\n",
      "ImportError: cannot import name 'astype_td64_unit_conversion' from 'pandas.core.dtypes.cast' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/dtypes/cast.py)\n",
      "]\n",
      "[autoreload of pandas.core.arrays failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/arrays/__init__.py\", line 20, in <module>\n",
      "    from pandas.core.arrays.string_arrow import ArrowStringArray\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/arrays/string_arrow.py\", line 21, in <module>\n",
      "    from pandas.compat import (\n",
      "ImportError: cannot import name 'pa_version_under1p0' from 'pandas.compat' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/compat/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.category failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 340, in <lambda>\n",
      "    lambda a, b: update_function(a.__func__, b.__func__)),\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: _simple_new() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of pandas.core.indexes.numeric failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: _convert_tolerance() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of pandas.core.indexes.datetimelike failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/indexes/datetimelike.py\", line 83, in <module>\n",
      "    class DatetimeIndexOpsMixin(NDArrayBackedExtensionIndex):\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/indexes/datetimelike.py\", line 598, in DatetimeIndexOpsMixin\n",
      "    @doc(Index._maybe_cast_listlike_indexer)\n",
      "AttributeError: type object 'Index' has no attribute '_maybe_cast_listlike_indexer'\n",
      "]\n",
      "[autoreload of pandas.core.indexes.datetimes failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/indexes/datetimes.py\", line 42, in <module>\n",
      "    from pandas.util._exceptions import find_stack_level\n",
      "ImportError: cannot import name 'find_stack_level' from 'pandas.util._exceptions' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/util/_exceptions.py)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.multi failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/indexes/multi.py\", line 28, in <module>\n",
      "    from pandas._libs.hashtable import duplicated\n",
      "ImportError: cannot import name 'duplicated' from 'pandas._libs.hashtable' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/_libs/hashtable.cpython-38-x86_64-linux-gnu.so)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.interval failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/indexes/interval.py\", line 39, in <module>\n",
      "    from pandas.core.dtypes.cast import (\n",
      "ImportError: cannot import name 'maybe_box_datetimelike' from 'pandas.core.dtypes.cast' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/dtypes/cast.py)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.period failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: asof_locs() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of pandas.core.indexes.range failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: get_indexer() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.indexes.api failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/indexes/api.py\", line 11, in <module>\n",
      "    from pandas.core.indexes.base import (\n",
      "ImportError: cannot import name 'get_unanimous_names' from 'pandas.core.indexes.base' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py)\n",
      "]\n",
      "[autoreload of pandas.core.indexing failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/indexing.py\", line 14, in <module>\n",
      "    from pandas._libs.indexing import NDFrameIndexerBase\n",
      "ImportError: cannot import name 'NDFrameIndexerBase' from 'pandas._libs.indexing' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/_libs/indexing.cpython-38-x86_64-linux-gnu.so)\n",
      "]\n",
      "[autoreload of pandas.core.internals.blocks failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/internals/blocks.py\", line 36, in <module>\n",
      "    from pandas.core.dtypes.cast import (\n",
      "ImportError: cannot import name 'astype_array_safe' from 'pandas.core.dtypes.cast' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/dtypes/cast.py)\n",
      "]\n",
      "[autoreload of pandas.core.internals.managers failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py\", line 34, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'is_1d_only_ea_dtype' from 'pandas.core.dtypes.common' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.internals.concat failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/internals/concat.py\", line 22, in <module>\n",
      "    from pandas.core.dtypes.cast import (\n",
      "ImportError: cannot import name 'ensure_dtype_can_hold_na' from 'pandas.core.dtypes.cast' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/dtypes/cast.py)\n",
      "]\n",
      "[autoreload of pandas.core.internals failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/internals/__init__.py\", line 1, in <module>\n",
      "    from pandas.core.internals.api import make_block  # pseudo-public version\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/internals/api.py\", line 23, in <module>\n",
      "    from pandas.core.internals.blocks import (\n",
      "ImportError: cannot import name 'check_ndim' from 'pandas.core.internals.blocks' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/internals/blocks.py)\n",
      "]\n",
      "[autoreload of pandas.io.common failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/common.py\", line 44, in <module>\n",
      "    from pandas.compat import (\n",
      "ImportError: cannot import name 'get_lzma_file' from 'pandas.compat' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/compat/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.core.generic failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/generic.py\", line 133, in <module>\n",
      "    from pandas.core.internals import (\n",
      "ImportError: cannot import name 'ArrayManager' from 'pandas.core.internals' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/internals/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.arrays failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/arrays/__init__.py\", line 6, in <module>\n",
      "    from pandas.core.arrays import (\n",
      "ImportError: cannot import name 'ArrowStringArray' from 'pandas.core.arrays' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/arrays/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.core.tools.datetimes failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/tools/datetimes.py\", line 31, in <module>\n",
      "    from pandas._libs.tslibs.parsing import (  # noqa\n",
      "ImportError: cannot import name 'format_is_iso' from 'pandas._libs.tslibs.parsing' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/_libs/tslibs/parsing.cpython-38-x86_64-linux-gnu.so)\n",
      "]\n",
      "[autoreload of pandas.core.window.rolling failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/window/rolling.py\", line 52, in <module>\n",
      "    from pandas.core.apply import ResamplerWindowApply\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/apply.py\", line 52, in <module>\n",
      "    from pandas.core.construction import (\n",
      "ImportError: cannot import name 'ensure_wrapped_if_datetimelike' from 'pandas.core.construction' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/construction.py)\n",
      "]\n",
      "[autoreload of pandas.core.window.ewm failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/window/ewm.py\", line 48, in <module>\n",
      "    from pandas.core.window.rolling import (\n",
      "ImportError: cannot import name 'BaseWindow' from 'pandas.core.window.rolling' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/window/rolling.py)\n",
      "]\n",
      "[autoreload of pandas.core.window.expanding failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/window/expanding.py\", line 34, in <module>\n",
      "    from pandas.core.window.rolling import (\n",
      "ImportError: cannot import name 'BaseWindowGroupby' from 'pandas.core.window.rolling' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/window/rolling.py)\n",
      "]\n",
      "[autoreload of pandas.core.window failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/window/__init__.py\", line 1, in <module>\n",
      "    from pandas.core.window.ewm import (  # noqa:F401\n",
      "ImportError: cannot import name 'ExponentialMovingWindowGroupby' from 'pandas.core.window.ewm' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/window/ewm.py)\n",
      "]\n",
      "[autoreload of pandas.core.series failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/series.py\", line 62, in <module>\n",
      "    from pandas.core.dtypes.cast import (\n",
      "ImportError: cannot import name 'maybe_box_native' from 'pandas.core.dtypes.cast' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/dtypes/cast.py)\n",
      "]\n",
      "[autoreload of pandas.core.internals.construction failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/internals/construction.py\", line 27, in <module>\n",
      "    from pandas.core.dtypes.cast import (\n",
      "ImportError: cannot import name 'dict_compat' from 'pandas.core.dtypes.cast' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/dtypes/cast.py)\n",
      "]\n",
      "[autoreload of pandas.core.reshape.concat failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/reshape/concat.py\", line 36, in <module>\n",
      "    from pandas.core.indexes.api import (\n",
      "ImportError: cannot import name 'get_unanimous_names' from 'pandas.core.indexes.api' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/indexes/api.py)\n",
      "]\n",
      "[autoreload of pandas.core.frame failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/frame.py\", line 46, in <module>\n",
      "    from pandas._libs.hashtable import duplicated\n",
      "ImportError: cannot import name 'duplicated' from 'pandas._libs.hashtable' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/_libs/hashtable.cpython-38-x86_64-linux-gnu.so)\n",
      "]\n",
      "[autoreload of pandas.core.groupby.grouper failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/groupby/grouper.py\", line 20, in <module>\n",
      "    from pandas.core.dtypes.cast import sanitize_to_nanoseconds\n",
      "ImportError: cannot import name 'sanitize_to_nanoseconds' from 'pandas.core.dtypes.cast' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/dtypes/cast.py)\n",
      "]\n",
      "[autoreload of pandas.core.groupby.ops failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/groupby/ops.py\", line 39, in <module>\n",
      "    from pandas.core.dtypes.cast import (\n",
      "ImportError: cannot import name 'maybe_cast_pointwise_result' from 'pandas.core.dtypes.cast' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/dtypes/cast.py)\n",
      "]\n",
      "[autoreload of pandas.core.groupby.groupby failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/groupby/groupby.py\", line 104, in <module>\n",
      "    from pandas.core.internals.blocks import ensure_block_shape\n",
      "ImportError: cannot import name 'ensure_block_shape' from 'pandas.core.internals.blocks' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/internals/blocks.py)\n",
      "]\n",
      "[autoreload of pandas.core.groupby.generic failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/groupby/generic.py\", line 69, in <module>\n",
      "    from pandas.core.apply import GroupByApply\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/apply.py\", line 52, in <module>\n",
      "    from pandas.core.construction import (\n",
      "ImportError: cannot import name 'ensure_wrapped_if_datetimelike' from 'pandas.core.construction' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/construction.py)\n",
      "]\n",
      "[autoreload of pandas.core.reshape.merge failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py\", line 81, in <module>\n",
      "    from pandas.core.internals import concatenate_managers\n",
      "ImportError: cannot import name 'concatenate_managers' from 'pandas.core.internals' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/internals/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.core.reshape.reshape failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/reshape/reshape.py\", line 17, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'is_1d_only_ea_dtype' from 'pandas.core.dtypes.common' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.io.excel._odfreader failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/excel/_odfreader.py\", line 14, in <module>\n",
      "    from pandas.io.excel._base import BaseExcelReader\n",
      "ImportError: cannot import name 'BaseExcelReader' from 'pandas.io.excel._base' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py)\n",
      "]\n",
      "[autoreload of pandas.io.excel._openpyxl failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py\", line 18, in <module>\n",
      "    from pandas.io.excel._base import (\n",
      "ImportError: cannot import name 'BaseExcelReader' from 'pandas.io.excel._base' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py)\n",
      "]\n",
      "[autoreload of pandas.io.excel._pyxlsb failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/excel/_pyxlsb.py\", line 10, in <module>\n",
      "    from pandas.io.excel._base import BaseExcelReader\n",
      "ImportError: cannot import name 'BaseExcelReader' from 'pandas.io.excel._base' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py)\n",
      "]\n",
      "[autoreload of pandas.io.excel._xlrd failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/excel/_xlrd.py\", line 8, in <module>\n",
      "    from pandas.io.excel._base import BaseExcelReader\n",
      "ImportError: cannot import name 'BaseExcelReader' from 'pandas.io.excel._base' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py)\n",
      "]\n",
      "[autoreload of pandas.io.excel._base failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py\", line 48, in <module>\n",
      "    from pandas.io.common import (\n",
      "ImportError: cannot import name 'IOHandles' from 'pandas.io.common' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/common.py)\n",
      "]\n",
      "[autoreload of pandas.io.formats.excel failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/formats/excel.py\", line 422, in <module>\n",
      "    class ExcelFormatter:\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/formats/excel.py\", line 781, in ExcelFormatter\n",
      "    @doc(storage_options=generic._shared_docs[\"storage_options\"])\n",
      "KeyError: 'storage_options'\n",
      "]\n",
      "[autoreload of pandas.io.excel failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/excel/__init__.py\", line 7, in <module>\n",
      "    from pandas.io.excel._openpyxl import OpenpyxlWriter as _OpenpyxlWriter\n",
      "ImportError: cannot import name 'OpenpyxlWriter' from 'pandas.io.excel._openpyxl' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py)\n",
      "]\n",
      "[autoreload of pandas.io.feather_format failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/feather_format.py\", line 22, in <module>\n",
      "    @doc(storage_options=generic._shared_docs[\"storage_options\"])\n",
      "KeyError: 'storage_options'\n",
      "]\n",
      "[autoreload of pandas.io.html failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: read_html() requires a code object with 4 free vars, not 5\n",
      "]\n",
      "[autoreload of pandas.io.json._json failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/json/_json.py\", line 54, in <module>\n",
      "    from pandas.io.common import (\n",
      "ImportError: cannot import name 'IOHandles' from 'pandas.io.common' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/common.py)\n",
      "]\n",
      "[autoreload of pandas.io.parquet failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/parquet.py\", line 28, in <module>\n",
      "    from pandas.io.common import (\n",
      "ImportError: cannot import name 'IOHandles' from 'pandas.io.common' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/common.py)\n",
      "]\n",
      "[autoreload of pandas.io.pickle failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/pickle.py\", line 19, in <module>\n",
      "    @doc(storage_options=generic._shared_docs[\"storage_options\"])\n",
      "KeyError: 'storage_options'\n",
      "]\n",
      "[autoreload of pandas.io.pytables failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/pytables.py\", line 89, in <module>\n",
      "    from pandas.core.internals import (\n",
      "ImportError: cannot import name 'ArrayManager' from 'pandas.core.internals' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/internals/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.io.stata failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/stata.py\", line 114, in <module>\n",
      "    {generic._shared_docs[\"storage_options\"]}\"\"\"\n",
      "KeyError: 'storage_options'\n",
      "]\n",
      "[autoreload of pandas.io.api failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/api.py\", line 40, in <module>\n",
      "    from pandas.io.xml import read_xml\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/xml.py\", line 27, in <module>\n",
      "    from pandas.io.common import (\n",
      "ImportError: cannot import name 'file_exists' from 'pandas.io.common' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/io/common.py)\n",
      "]\n",
      "[autoreload of pandas failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/usr/local/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/usr/local/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/home/cdsw/.local/lib/python3.8/site-packages/pandas/__init__.py\", line 22, in <module>\n",
      "    from pandas.compat import (\n",
      "ImportError: cannot import name 'np_version_under1p18' from 'pandas.compat' (/home/cdsw/.local/lib/python3.8/site-packages/pandas/compat/__init__.py)\n",
      "]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The autoreload extension is already loaded. To reload it, use:\n",
      "  %reload_ext autoreload\n",
      "The lab_black extension is already loaded. To reload it, use:\n",
      "  %reload_ext lab_black\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import sys\n",
    "import cdsw\n",
    "import pickle\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from pandas.tseries.offsets import DateOffset\n",
    "\n",
    "# Install cmlapi package\n",
    "try:\n",
    "    import cmlapi\n",
    "except ModuleNotFoundError:\n",
    "    import os\n",
    "\n",
    "    cluster = os.getenv(\"CDSW_API_URL\")[:-1] + \"2\"\n",
    "    !pip3 install {cluster}/python.tar.gz\n",
    "    import cmlapi\n",
    "\n",
    "from utils.utils import get_latest_deployment_details\n",
    "from utils.inference_utils import ThreadedModelRequest, cast_date_as_str_for_json\n",
    "\n",
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "%load_ext lab_black"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9f58cdd0-96d3-4a66-8398-d1849a6b80ad",
   "metadata": {},
   "source": [
    "## Simulation"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c7eb2ff2-9e34-4aea-a1bc-5f683d027ed7",
   "metadata": {},
   "source": [
    "### 1. Score Train Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "d40c3d88-0a0f-43c7-94da-24db98c79baa",
   "metadata": {},
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "Can't get attribute 'new_block' on <module 'pandas.core.internals.blocks' from '/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/internals/blocks.py'>",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-4-b72845f2d514>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# format train data for inference\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0mtrain_df\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mpd\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mread_pickle\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"../data/working/train_df.pkl\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m \u001b[0mtrain_records\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcast_date_as_str_for_json\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtrain_df\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mto_dict\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0morient\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m\"records\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/pandas/io/pickle.py\u001b[0m in \u001b[0;36mread_pickle\u001b[0;34m(filepath_or_buffer, compression)\u001b[0m\n\u001b[1;32m    185\u001b[0m             \u001b[0;31m#  \"No module named 'pandas.core.sparse.series'\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    186\u001b[0m             \u001b[0;31m#  \"Can't get attribute '__nat_unpickle' on <module 'pandas._libs.tslib\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 187\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mpc\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mload\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mf\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mencoding\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mNone\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    188\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0mUnicodeDecodeError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    189\u001b[0m         \u001b[0;31m# e.g. can occur for files written in py27; see GH#28645 and GH#31988\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/pandas/compat/pickle_compat.py\u001b[0m in \u001b[0;36mload\u001b[0;34m(fh, encoding, is_verbose)\u001b[0m\n\u001b[1;32m    247\u001b[0m         \u001b[0mup\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mis_verbose\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mis_verbose\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    248\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 249\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mup\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mload\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    250\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mValueError\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    251\u001b[0m         \u001b[0;32mraise\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/lib/python3.8/pickle.py\u001b[0m in \u001b[0;36mload\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1210\u001b[0m                     \u001b[0;32mraise\u001b[0m \u001b[0mEOFError\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1211\u001b[0m                 \u001b[0;32massert\u001b[0m \u001b[0misinstance\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mkey\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbytes_types\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1212\u001b[0;31m                 \u001b[0mdispatch\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mkey\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1213\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0m_Stop\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mstopinst\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1214\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0mstopinst\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mvalue\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/lib/python3.8/pickle.py\u001b[0m in \u001b[0;36mload_stack_global\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1535\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mtype\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mstr\u001b[0m \u001b[0;32mor\u001b[0m \u001b[0mtype\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmodule\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mstr\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1536\u001b[0m             \u001b[0;32mraise\u001b[0m \u001b[0mUnpicklingError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"STACK_GLOBAL requires str\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1537\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mappend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfind_class\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmodule\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mname\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1538\u001b[0m     \u001b[0mdispatch\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mSTACK_GLOBAL\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mload_stack_global\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1539\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/pandas/compat/pickle_compat.py\u001b[0m in \u001b[0;36mfind_class\u001b[0;34m(self, module, name)\u001b[0m\n\u001b[1;32m    187\u001b[0m         \u001b[0mkey\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mmodule\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mname\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    188\u001b[0m         \u001b[0mmodule\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mname\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_class_locations_map\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mkey\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mkey\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 189\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0msuper\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfind_class\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmodule\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mname\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    190\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    191\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/lib/python3.8/pickle.py\u001b[0m in \u001b[0;36mfind_class\u001b[0;34m(self, module, name)\u001b[0m\n\u001b[1;32m   1579\u001b[0m         \u001b[0m__import__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmodule\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlevel\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1580\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mproto\u001b[0m \u001b[0;34m>=\u001b[0m \u001b[0;36m4\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1581\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0m_getattribute\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msys\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmodules\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mmodule\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mname\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1582\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1583\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0mgetattr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msys\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmodules\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mmodule\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mname\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/lib/python3.8/pickle.py\u001b[0m in \u001b[0;36m_getattribute\u001b[0;34m(obj, name)\u001b[0m\n\u001b[1;32m    329\u001b[0m             \u001b[0mobj\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mgetattr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mobj\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msubpath\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    330\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mAttributeError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 331\u001b[0;31m             raise AttributeError(\"Can't get attribute {!r} on {!r}\"\n\u001b[0m\u001b[1;32m    332\u001b[0m                                  .format(name, obj)) from None\n\u001b[1;32m    333\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0mobj\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mparent\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mAttributeError\u001b[0m: Can't get attribute 'new_block' on <module 'pandas.core.internals.blocks' from '/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/internals/blocks.py'>"
     ]
    }
   ],
   "source": [
    "# format train data for inference\n",
    "train_df = pd.read_pickle(\"../data/working/train_df.pkl\")\n",
    "train_records = cast_date_as_str_for_json(train_df).to_dict(orient=\"records\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "efe9e39b-3b6f-45b8-b43e-1b7cfee70251",
   "metadata": {},
   "outputs": [],
   "source": [
    "# obtain model deployment info\n",
    "client = cmlapi.default_client()\n",
    "latest_deployment_details = get_latest_deployment_details(\n",
    "    client=client, model_name=\"Price Regressor8\"\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "203331ab-4d5d-483f-953e-4aa233947d30",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 42 s, sys: 1.16 s, total: 43.1 s\n",
      "Wall time: 7min 1s\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "tmr = ThreadedModelRequest(deployment_details=latest_deployment_details)\n",
    "train_inference_metadata = tmr.threaded_call(train_records)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "65bd2493-0128-4d39-8920-61ce0146e492",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "11741"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(train_inference_metadata[\"id_uuid_mapping\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "ace65ef6-515d-4e8c-8323-6973f7a3af39",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "# with open(\"train_inference_metadata.pkl\", \"wb\") as f:\n",
    "#     pickle.dump(train_inference_metadata, f)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "ce21cf30-b4e0-45c7-b18c-56a904687a38",
   "metadata": {},
   "outputs": [],
   "source": [
    "# with open(\"train_inference_metadata.pkl\", \"rb\") as f:\n",
    "#     train_inference_metadata = pickle.load(f)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "22e033e7-daae-4a8b-a677-4801db220d0d",
   "metadata": {},
   "source": [
    "#### Create master id <--> uuid mapping: this gets populated as soon as a property is \"listed\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "beab0343-de3e-42c2-b96d-dde827437856",
   "metadata": {},
   "outputs": [],
   "source": [
    "master_id_uuid_mapping = {}\n",
    "master_id_uuid_mapping.update(train_inference_metadata[\"id_uuid_mapping\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "381a594a-e526-4158-a145-533103c4e08a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "11741"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(master_id_uuid_mapping)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bb9fcdc8-1f97-418f-b2ae-4c31bca006ff",
   "metadata": {},
   "source": [
    "### 1.a Add delayed metrics"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "824d0ac8-4ce4-4ba3-9fe1-a4f5fbab1d6c",
   "metadata": {},
   "outputs": [],
   "source": [
    "def add_delayed_metrics(uuids, ground_truths, sold_dates):\n",
    "    \"\"\"\n",
    "    Add delayed metrics to CML Model Metrics database provided a\n",
    "    list of prediction UUID's and corresponding list of ground truth values.\n",
    "\n",
    "    \"\"\"\n",
    "\n",
    "    if len(uuids) != len(ground_truths) != len(sold_dates):\n",
    "        raise ValueError(\n",
    "            \"UUIDs, ground_truths, and sold_dates must be of same length and correspond by index.\"\n",
    "        )\n",
    "\n",
    "    for uuid, gt, ds in zip(uuids, ground_truths, sold_dates):\n",
    "        cdsw.track_delayed_metrics(\n",
    "            metrics={\"ground_truth\": gt, \"date_sold\": ds}, prediction_uuid=uuid\n",
    "        )\n",
    "\n",
    "    print(f\"Sucessfully added ground truth values to {len(uuids)} records.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "110f5060-81d2-4897-a7d4-eb4d564ed300",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "# get list of uuids from train_inference_metadata\n",
    "train_uuids = list(train_inference_metadata[\"id_uuid_mapping\"].values())\n",
    "\n",
    "# get list of prices\n",
    "train_gts = train_df[\n",
    "    train_df.id.isin(train_inference_metadata[\"id_uuid_mapping\"].keys())\n",
    "].price.tolist()\n",
    "\n",
    "# get list of sold_dates\n",
    "train_sold_dates = train_df[\n",
    "    train_df.id.isin(train_inference_metadata[\"id_uuid_mapping\"].keys())\n",
    "].date_sold.tolist()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "4e636bf5-61d0-4955-8c7e-355975eaf4b8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Sucessfully added ground truth values to 11741 records.\n",
      "CPU times: user 2min 3s, sys: 3.94 s, total: 2min 7s\n",
      "Wall time: 3min 45s\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "\n",
    "add_delayed_metrics(train_uuids, train_gts, train_sold_dates)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "744d5f5c-ae64-4437-9420-a95781758d0a",
   "metadata": {},
   "source": [
    "### 1.b Query the metadata store"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "8cae099c-f937-49cb-9a87-8158614f63be",
   "metadata": {},
   "outputs": [],
   "source": [
    "metrics = cdsw.read_metrics(\n",
    "    model_deployment_crn=latest_deployment_details[\"latest_deployment_crn\"],\n",
    "    start_timestamp_ms=train_inference_metadata[\"start_timestamp_ms\"],\n",
    "    end_timestamp_ms=train_inference_metadata[\"end_timestamp_ms\"],\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "49dded32-5f96-45d0-b11e-db67ddb07b85",
   "metadata": {},
   "outputs": [],
   "source": [
    "from typing import Dict\n",
    "\n",
    "\n",
    "def format_model_metrics_query(metrics: Dict):\n",
    "    \"\"\"\n",
    "    Accepts the response dictionary from `cdsw.read_metrics()`, filters out any non-metrics columns,\n",
    "    and formats as Dataframe.\n",
    "    \"\"\"\n",
    "    metrics = pd.json_normalize(metrics[\"metrics\"])\n",
    "\n",
    "    return metrics[\n",
    "        [col for col in metrics.columns if col.split(\".\")[0] == \"metrics\"]\n",
    "        + [\"predictionUuid\"]\n",
    "    ].rename(columns={col: col.split(\".\")[-1] for col in metrics.columns})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "dc75642d-9c36-49bd-a793-23ece8d0efa9",
   "metadata": {},
   "outputs": [],
   "source": [
    "train_metrics_df = format_model_metrics_query(metrics)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "9ee9f04a-e893-415a-a959-5e105ae32eeb",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>date_sold</th>\n",
       "      <th>ground_truth</th>\n",
       "      <th>view</th>\n",
       "      <th>zipcode</th>\n",
       "      <th>bedrooms</th>\n",
       "      <th>sqft_lot</th>\n",
       "      <th>bathrooms</th>\n",
       "      <th>condition</th>\n",
       "      <th>waterfront</th>\n",
       "      <th>sqft_living</th>\n",
       "      <th>predicted_result</th>\n",
       "      <th>predictionUuid</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2014-07-25</td>\n",
       "      <td>275000.0</td>\n",
       "      <td>0</td>\n",
       "      <td>98030</td>\n",
       "      <td>4</td>\n",
       "      <td>26114</td>\n",
       "      <td>1.00</td>\n",
       "      <td>5</td>\n",
       "      <td>0</td>\n",
       "      <td>1080</td>\n",
       "      <td>228819.312958</td>\n",
       "      <td>c6763e95-3460-487c-8a0a-fdf95e9a1267</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2014-09-26</td>\n",
       "      <td>775000.0</td>\n",
       "      <td>0</td>\n",
       "      <td>98077</td>\n",
       "      <td>4</td>\n",
       "      <td>34513</td>\n",
       "      <td>2.50</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>3890</td>\n",
       "      <td>815129.692229</td>\n",
       "      <td>6e442c4f-572f-4f54-ae48-07454343fb08</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2014-07-21</td>\n",
       "      <td>265000.0</td>\n",
       "      <td>0</td>\n",
       "      <td>98022</td>\n",
       "      <td>3</td>\n",
       "      <td>10489</td>\n",
       "      <td>1.50</td>\n",
       "      <td>5</td>\n",
       "      <td>0</td>\n",
       "      <td>1560</td>\n",
       "      <td>262579.397453</td>\n",
       "      <td>4b45150c-988a-44a4-aee4-f910a20feaa9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2014-07-22</td>\n",
       "      <td>372500.0</td>\n",
       "      <td>0</td>\n",
       "      <td>98126</td>\n",
       "      <td>2</td>\n",
       "      <td>2958</td>\n",
       "      <td>2.50</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>1400</td>\n",
       "      <td>377354.064458</td>\n",
       "      <td>86668c4e-4a63-44c8-a043-ca966e4dd3b7</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2014-06-03</td>\n",
       "      <td>235000.0</td>\n",
       "      <td>0</td>\n",
       "      <td>98056</td>\n",
       "      <td>3</td>\n",
       "      <td>15603</td>\n",
       "      <td>1.00</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>1250</td>\n",
       "      <td>288589.081822</td>\n",
       "      <td>51f4e54c-eff2-41a6-86a2-1088f657c4a5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11736</th>\n",
       "      <td>2014-05-02</td>\n",
       "      <td>308500.0</td>\n",
       "      <td>0</td>\n",
       "      <td>98155</td>\n",
       "      <td>2</td>\n",
       "      <td>6174</td>\n",
       "      <td>1.00</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>850</td>\n",
       "      <td>287682.216986</td>\n",
       "      <td>bf47bf4d-fd2b-4f2d-b3bc-b66340f445dd</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11737</th>\n",
       "      <td>2014-10-27</td>\n",
       "      <td>1049990.0</td>\n",
       "      <td>0</td>\n",
       "      <td>98053</td>\n",
       "      <td>5</td>\n",
       "      <td>9588</td>\n",
       "      <td>3.25</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>4240</td>\n",
       "      <td>993825.418767</td>\n",
       "      <td>206b1531-28e7-42b6-8320-567fc93441c0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11738</th>\n",
       "      <td>2014-06-10</td>\n",
       "      <td>589900.0</td>\n",
       "      <td>0</td>\n",
       "      <td>98027</td>\n",
       "      <td>4</td>\n",
       "      <td>35889</td>\n",
       "      <td>4.50</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>3870</td>\n",
       "      <td>875723.661588</td>\n",
       "      <td>d24a3379-5fc8-4a90-9491-fafd9d9a29d6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11739</th>\n",
       "      <td>2014-07-08</td>\n",
       "      <td>600000.0</td>\n",
       "      <td>0</td>\n",
       "      <td>98034</td>\n",
       "      <td>4</td>\n",
       "      <td>11370</td>\n",
       "      <td>2.50</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>2250</td>\n",
       "      <td>500175.417481</td>\n",
       "      <td>8a5a34da-fd62-440f-9895-613038ae7a13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11740</th>\n",
       "      <td>2014-07-16</td>\n",
       "      <td>389500.0</td>\n",
       "      <td>0</td>\n",
       "      <td>98136</td>\n",
       "      <td>3</td>\n",
       "      <td>874</td>\n",
       "      <td>2.50</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>1350</td>\n",
       "      <td>435048.320229</td>\n",
       "      <td>04192ead-364f-48b4-bf85-62f89b33ea4c</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>11741 rows × 12 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "        date_sold  ground_truth  view  zipcode  bedrooms  sqft_lot  bathrooms  \\\n",
       "0      2014-07-25      275000.0     0    98030         4     26114       1.00   \n",
       "1      2014-09-26      775000.0     0    98077         4     34513       2.50   \n",
       "2      2014-07-21      265000.0     0    98022         3     10489       1.50   \n",
       "3      2014-07-22      372500.0     0    98126         2      2958       2.50   \n",
       "4      2014-06-03      235000.0     0    98056         3     15603       1.00   \n",
       "...           ...           ...   ...      ...       ...       ...        ...   \n",
       "11736  2014-05-02      308500.0     0    98155         2      6174       1.00   \n",
       "11737  2014-10-27     1049990.0     0    98053         5      9588       3.25   \n",
       "11738  2014-06-10      589900.0     0    98027         4     35889       4.50   \n",
       "11739  2014-07-08      600000.0     0    98034         4     11370       2.50   \n",
       "11740  2014-07-16      389500.0     0    98136         3       874       2.50   \n",
       "\n",
       "       condition  waterfront  sqft_living  predicted_result  \\\n",
       "0              5           0         1080     228819.312958   \n",
       "1              3           0         3890     815129.692229   \n",
       "2              5           0         1560     262579.397453   \n",
       "3              3           0         1400     377354.064458   \n",
       "4              4           0         1250     288589.081822   \n",
       "...          ...         ...          ...               ...   \n",
       "11736          4           0          850     287682.216986   \n",
       "11737          3           0         4240     993825.418767   \n",
       "11738          3           0         3870     875723.661588   \n",
       "11739          3           0         2250     500175.417481   \n",
       "11740          3           0         1350     435048.320229   \n",
       "\n",
       "                             predictionUuid  \n",
       "0      c6763e95-3460-487c-8a0a-fdf95e9a1267  \n",
       "1      6e442c4f-572f-4f54-ae48-07454343fb08  \n",
       "2      4b45150c-988a-44a4-aee4-f910a20feaa9  \n",
       "3      86668c4e-4a63-44c8-a043-ca966e4dd3b7  \n",
       "4      51f4e54c-eff2-41a6-86a2-1088f657c4a5  \n",
       "...                                     ...  \n",
       "11736  bf47bf4d-fd2b-4f2d-b3bc-b66340f445dd  \n",
       "11737  206b1531-28e7-42b6-8320-567fc93441c0  \n",
       "11738  d24a3379-5fc8-4a90-9491-fafd9d9a29d6  \n",
       "11739  8a5a34da-fd62-440f-9895-613038ae7a13  \n",
       "11740  04192ead-364f-48b4-bf85-62f89b33ea4c  \n",
       "\n",
       "[11741 rows x 12 columns]"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "train_metrics_df"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a83e4187-9ad5-487b-b272-71c3e15fd9dd",
   "metadata": {},
   "source": [
    "### 2. Create Simulation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "21172b7b-e40c-48f0-a860-ba9ef5b4eb2c",
   "metadata": {},
   "outputs": [],
   "source": [
    "prod_path = \"../data/working/prod_df.pkl\"\n",
    "prod_df = pd.read_pickle(prod_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "264d1e91-a945-4800-a65c-c7847c6f9f2f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# number of months in prod set\n",
    "n_months = int(\n",
    "    np.ceil(\n",
    "        (prod_df.date_sold.max() - prod_df.date_sold.min()) / np.timedelta64(1, \"M\")\n",
    "    )\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "c7500d86-48c7-462f-b216-5067f5dcae78",
   "metadata": {},
   "outputs": [],
   "source": [
    "# construct date ranges to iterate through as simulation of time (include left, exclude right)\n",
    "\n",
    "date_ranges = [\n",
    "    [\n",
    "        (prod_df.date_sold.min() + DateOffset(months=n)),\n",
    "        (prod_df.date_sold.min() + DateOffset(months=n + 2)),\n",
    "    ]\n",
    "    for n in range(0, n_months, 2)\n",
    "]\n",
    "\n",
    "# increase first date range to account for records that listed during the train_df timeframe\n",
    "date_ranges[0][0] = date_ranges[0][0] - DateOffset(years=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "0236394d-651b-48a7-b936-7893caa4fe2f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[[Timestamp('2013-11-01 00:00:00'), Timestamp('2015-01-01 00:00:00')],\n",
       " [Timestamp('2015-01-01 00:00:00'), Timestamp('2015-03-01 00:00:00')],\n",
       " [Timestamp('2015-03-01 00:00:00'), Timestamp('2015-05-01 00:00:00')],\n",
       " [Timestamp('2015-05-01 00:00:00'), Timestamp('2015-07-01 00:00:00')]]"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "date_ranges"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "eb7d0d67-9d66-4eab-ad4e-b0f0d9eaf78f",
   "metadata": {},
   "source": [
    "### Logic for one loop"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ac79c501-7798-4f01-9bad-15a068d7c000",
   "metadata": {},
   "source": [
    "#### Query prod_df for new listings in new date range + make inference"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "8591e9c5-627d-493f-ae4a-0de3b98c3823",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/cdsw/.local/lib/python3.8/site-packages/pandas/core/indexing.py:1773: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  self._setitem_single_column(ilocs[0], value, pi)\n"
     ]
    }
   ],
   "source": [
    "new_listings_records = prod_df.loc[\n",
    "    prod_df.date_listed.between(date_ranges[0][0], date_ranges[0][1], inclusive=\"left\")\n",
    "]\n",
    "\n",
    "new_listings_records = cast_date_as_str_for_json(new_listings_records).to_dict(\n",
    "    orient=\"records\"\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "f7b988cc-fc4f-43f3-9731-f67b98baf6ba",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 13.6 s, sys: 310 ms, total: 13.9 s\n",
      "Wall time: 2min 16s\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "tmr = ThreadedModelRequest(deployment_details=latest_deployment_details)\n",
    "new_listing_inference_metadata = tmr.threaded_call(new_listings_records)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "08e39a4b-225f-498d-8828-9c30bde40867",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "3840"
      ]
     },
     "execution_count": 27,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(new_listing_inference_metadata[\"id_uuid_mapping\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "541e637d-bfc2-498b-bbf8-d8f55c1be735",
   "metadata": {},
   "outputs": [],
   "source": [
    "master_id_uuid_mapping.update(new_listing_inference_metadata[\"id_uuid_mapping\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "bab2345c-22a4-49af-889f-f2a1591e9baf",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "15581"
      ]
     },
     "execution_count": 29,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(master_id_uuid_mapping)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "68d6f5d1-fff8-43c4-a82d-34c7894fcb91",
   "metadata": {},
   "source": [
    "#### Query prod_df for newly sold properties in new date range + assign ground truth to records in metric store"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "f4ad00e7-2f12-4849-954b-c07d1477a0d2",
   "metadata": {},
   "outputs": [],
   "source": [
    "new_sold_records = prod_df.loc[\n",
    "    prod_df.date_sold.between(date_ranges[0][0], date_ranges[0][1], inclusive=\"left\")\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "c351911d-720e-4f9d-bca2-690fedafada2",
   "metadata": {},
   "outputs": [],
   "source": [
    "# get list of uuids from train_inference_metadata\n",
    "new_sold_uuids = new_sold_records.id.apply(lambda x: master_id_uuid_mapping[x]).tolist()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "1f6e21fa-ecc8-47f7-9fce-691e18c14932",
   "metadata": {},
   "outputs": [],
   "source": [
    "# get list of ground truth prices for newly sold properties\n",
    "new_sold_gts = prod_df[prod_df.id.isin(new_sold_records.id)].price.tolist()\n",
    "\n",
    "# get list of sold_dates for newly sold properties\n",
    "new_sold_dates = (\n",
    "    prod_df[prod_df.id.isin(new_sold_records.id)].date_sold.astype(str).tolist()\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "id": "dcd75559-5d8a-4148-b90a-b180e5f19b58",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Sucessfully added ground truth values to 2858 records.\n",
      "CPU times: user 30.2 s, sys: 1.09 s, total: 31.3 s\n",
      "Wall time: 55 s\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "add_delayed_metrics(new_sold_uuids, new_sold_gts, new_sold_dates)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "777730ae-814c-4e56-8a14-2294fa056318",
   "metadata": {},
   "source": [
    "#### Query metric store for newly sold records for evidently reporting"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "id": "743bab9f-63b4-4a08-b310-dbd577fa76aa",
   "metadata": {},
   "outputs": [],
   "source": [
    "# because I cant query by UUID, I must query all records, then filter to new_sold by uuid\n",
    "metrics = cdsw.read_metrics(\n",
    "    model_deployment_crn=latest_deployment_details[\"latest_deployment_crn\"]\n",
    ")\n",
    "\n",
    "metrics_df = format_model_metrics_query(metrics)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "id": "0a6651ff-2d8d-4326-be4f-c082222ed568",
   "metadata": {},
   "outputs": [],
   "source": [
    "new_sold_metrics_df = metrics_df[metrics_df.predictionUuid.isin(new_sold_uuids)]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "id": "35f23f07-9d42-4180-9d8e-21f35b137483",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>date_sold</th>\n",
       "      <th>ground_truth</th>\n",
       "      <th>view</th>\n",
       "      <th>zipcode</th>\n",
       "      <th>bedrooms</th>\n",
       "      <th>sqft_lot</th>\n",
       "      <th>bathrooms</th>\n",
       "      <th>condition</th>\n",
       "      <th>waterfront</th>\n",
       "      <th>sqft_living</th>\n",
       "      <th>predicted_result</th>\n",
       "      <th>predictionUuid</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>11741</th>\n",
       "      <td>2014-11-01</td>\n",
       "      <td>353000.0</td>\n",
       "      <td>0</td>\n",
       "      <td>98115</td>\n",
       "      <td>3</td>\n",
       "      <td>864</td>\n",
       "      <td>2.50</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>1250</td>\n",
       "      <td>4.823624e+05</td>\n",
       "      <td>547c8268-533d-44f3-b0dd-ac288048e513</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11742</th>\n",
       "      <td>2014-11-01</td>\n",
       "      <td>1750000.0</td>\n",
       "      <td>0</td>\n",
       "      <td>98004</td>\n",
       "      <td>4</td>\n",
       "      <td>8975</td>\n",
       "      <td>2.75</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>3560</td>\n",
       "      <td>1.351848e+06</td>\n",
       "      <td>aed80c8e-8013-4d64-9648-642ebb0125e4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11743</th>\n",
       "      <td>2014-11-01</td>\n",
       "      <td>644500.0</td>\n",
       "      <td>0</td>\n",
       "      <td>98074</td>\n",
       "      <td>4</td>\n",
       "      <td>5342</td>\n",
       "      <td>2.50</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>2990</td>\n",
       "      <td>6.780784e+05</td>\n",
       "      <td>eb8dc1e6-a418-454a-9bbe-45587c05f582</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11744</th>\n",
       "      <td>2014-11-01</td>\n",
       "      <td>399000.0</td>\n",
       "      <td>0</td>\n",
       "      <td>98065</td>\n",
       "      <td>3</td>\n",
       "      <td>3690</td>\n",
       "      <td>2.50</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>1740</td>\n",
       "      <td>3.829369e+05</td>\n",
       "      <td>2323a343-789a-4559-b360-1bc34627f8dd</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11745</th>\n",
       "      <td>2014-11-02</td>\n",
       "      <td>825000.0</td>\n",
       "      <td>0</td>\n",
       "      <td>98117</td>\n",
       "      <td>4</td>\n",
       "      <td>4000</td>\n",
       "      <td>2.50</td>\n",
       "      <td>5</td>\n",
       "      <td>0</td>\n",
       "      <td>2560</td>\n",
       "      <td>7.390113e+05</td>\n",
       "      <td>585a579c-e08e-45d0-8de4-c5e39789b848</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14594</th>\n",
       "      <td>2014-12-31</td>\n",
       "      <td>261000.0</td>\n",
       "      <td>0</td>\n",
       "      <td>98038</td>\n",
       "      <td>3</td>\n",
       "      <td>7686</td>\n",
       "      <td>1.75</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>1350</td>\n",
       "      <td>2.635794e+05</td>\n",
       "      <td>26b40278-706b-4df9-add9-178653007172</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14595</th>\n",
       "      <td>2014-12-31</td>\n",
       "      <td>665000.0</td>\n",
       "      <td>0</td>\n",
       "      <td>98075</td>\n",
       "      <td>4</td>\n",
       "      <td>5936</td>\n",
       "      <td>2.50</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>2510</td>\n",
       "      <td>6.063297e+05</td>\n",
       "      <td>09d5f10a-de06-4bad-9973-d924f61c4e51</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14596</th>\n",
       "      <td>2014-12-31</td>\n",
       "      <td>219200.0</td>\n",
       "      <td>0</td>\n",
       "      <td>98002</td>\n",
       "      <td>3</td>\n",
       "      <td>7000</td>\n",
       "      <td>2.00</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>1680</td>\n",
       "      <td>2.355372e+05</td>\n",
       "      <td>e4ab0287-7cd6-4fd7-a33a-d725d43b24f8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14597</th>\n",
       "      <td>2014-12-31</td>\n",
       "      <td>310000.0</td>\n",
       "      <td>0</td>\n",
       "      <td>98133</td>\n",
       "      <td>3</td>\n",
       "      <td>1361</td>\n",
       "      <td>2.00</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>1310</td>\n",
       "      <td>3.323658e+05</td>\n",
       "      <td>9580dce7-a862-44c6-815c-491b548c094d</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14642</th>\n",
       "      <td>2014-12-29</td>\n",
       "      <td>230000.0</td>\n",
       "      <td>0</td>\n",
       "      <td>98118</td>\n",
       "      <td>2</td>\n",
       "      <td>5913</td>\n",
       "      <td>1.00</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>720</td>\n",
       "      <td>2.649332e+05</td>\n",
       "      <td>6b239e28-ae2b-4871-82fb-0afb5b8117a0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>2858 rows × 12 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "        date_sold  ground_truth  view  zipcode  bedrooms  sqft_lot  bathrooms  \\\n",
       "11741  2014-11-01      353000.0     0    98115         3       864       2.50   \n",
       "11742  2014-11-01     1750000.0     0    98004         4      8975       2.75   \n",
       "11743  2014-11-01      644500.0     0    98074         4      5342       2.50   \n",
       "11744  2014-11-01      399000.0     0    98065         3      3690       2.50   \n",
       "11745  2014-11-02      825000.0     0    98117         4      4000       2.50   \n",
       "...           ...           ...   ...      ...       ...       ...        ...   \n",
       "14594  2014-12-31      261000.0     0    98038         3      7686       1.75   \n",
       "14595  2014-12-31      665000.0     0    98075         4      5936       2.50   \n",
       "14596  2014-12-31      219200.0     0    98002         3      7000       2.00   \n",
       "14597  2014-12-31      310000.0     0    98133         3      1361       2.00   \n",
       "14642  2014-12-29      230000.0     0    98118         2      5913       1.00   \n",
       "\n",
       "       condition  waterfront  sqft_living  predicted_result  \\\n",
       "11741          3           0         1250      4.823624e+05   \n",
       "11742          3           0         3560      1.351848e+06   \n",
       "11743          3           0         2990      6.780784e+05   \n",
       "11744          3           0         1740      3.829369e+05   \n",
       "11745          5           0         2560      7.390113e+05   \n",
       "...          ...         ...          ...               ...   \n",
       "14594          3           0         1350      2.635794e+05   \n",
       "14595          3           0         2510      6.063297e+05   \n",
       "14596          4           0         1680      2.355372e+05   \n",
       "14597          3           0         1310      3.323658e+05   \n",
       "14642          3           0          720      2.649332e+05   \n",
       "\n",
       "                             predictionUuid  \n",
       "11741  547c8268-533d-44f3-b0dd-ac288048e513  \n",
       "11742  aed80c8e-8013-4d64-9648-642ebb0125e4  \n",
       "11743  eb8dc1e6-a418-454a-9bbe-45587c05f582  \n",
       "11744  2323a343-789a-4559-b360-1bc34627f8dd  \n",
       "11745  585a579c-e08e-45d0-8de4-c5e39789b848  \n",
       "...                                     ...  \n",
       "14594  26b40278-706b-4df9-add9-178653007172  \n",
       "14595  09d5f10a-de06-4bad-9973-d924f61c4e51  \n",
       "14596  e4ab0287-7cd6-4fd7-a33a-d725d43b24f8  \n",
       "14597  9580dce7-a862-44c6-815c-491b548c094d  \n",
       "14642  6b239e28-ae2b-4871-82fb-0afb5b8117a0  \n",
       "\n",
       "[2858 rows x 12 columns]"
      ]
     },
     "execution_count": 51,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "new_sold_metrics_df"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d1ce2a07-fed7-409f-95c6-e93bd92f5ea9",
   "metadata": {},
   "source": [
    "## Build Reporting Dashboard"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "id": "e075f619-f712-4ff1-b2cc-7e3d7d17171d",
   "metadata": {},
   "outputs": [],
   "source": [
    "from evidently.dashboard import Dashboard\n",
    "from evidently.tabs import DataDriftTab, NumTargetDriftTab, RegressionPerformanceTab"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "id": "665b7b4c-5412-445e-9ecf-6fe8cc2a9631",
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "calculate() missing 2 required positional arguments: 'reference_data' and 'current_data'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-56-1ace46168626>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     13\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     14\u001b[0m \u001b[0mdashboard\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mDashboard\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtabs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mDataDriftTab\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mNumTargetDriftTab\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mRegressionPerformanceTab\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 15\u001b[0;31m \u001b[0mdashboard\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcalculate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m: calculate() missing 2 required positional arguments: 'reference_data' and 'current_data'"
     ]
    }
   ],
   "source": [
    "TARGET = 'ground_truth'\n",
    "PREDICTION = 'predicted_result'\n",
    "NUM_FEATURES = [\"bedrooms\", \"bathrooms\", \"sqft_living\", \"sqft_lot\"]\n",
    "CAT_FEATURES = [\"waterfront\", \"zipcode\", \"condition\", \"view\"]\n",
    "\n",
    "\n",
    "column_map = {\n",
    "    'target': TARGET,\n",
    "    'prediction': PREDICTION,\n",
    "    'numerical_features': NUM_FEATURES,\n",
    "    'categorical_features': CAT_FEATURES\n",
    "}\n",
    "\n",
    "dashboard = Dashboard(tabs=[DataDriftTab, NumTargetDriftTab, RegressionPerformanceTab])\n",
    "dashboard.calculate(reference_data=)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "id": "61a1bc25-743e-4dc6-83f6-f88e021fb542",
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "descriptor 'axes' for 'BlockManager' objects doesn't apply to a 'BlockManager' object",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-60-66541c044c6f>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mtrain_metrics_df\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mhead\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/pandas/core/generic.py\u001b[0m in \u001b[0;36mhead\u001b[0;34m(self, n)\u001b[0m\n\u001b[1;32m   4712\u001b[0m         \u001b[0;36m5\u001b[0m     \u001b[0mparrot\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   4713\u001b[0m         \"\"\"\n\u001b[0;32m-> 4714\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0miloc\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0mn\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   4715\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   4716\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mtail\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mFrameOrSeries\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mn\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mint\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m5\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m->\u001b[0m \u001b[0mFrameOrSeries\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/pandas/core/indexing.py\u001b[0m in \u001b[0;36m__getitem__\u001b[0;34m(self, key)\u001b[0m\n\u001b[1;32m    929\u001b[0m         \u001b[0mbool\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    930\u001b[0m         \"\"\"\n\u001b[0;32m--> 931\u001b[0;31m         \u001b[0;31m# this is a shortcut accessor to both .loc and .iloc\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    932\u001b[0m         \u001b[0;31m# that provide the equivalent access of .at and .iat\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    933\u001b[0m         \u001b[0;31m# a) avoid getting things via sections and (to minimize dtype changes)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/pandas/core/indexing.py\u001b[0m in \u001b[0;36m_getitem_axis\u001b[0;34m(self, key, axis)\u001b[0m\n\u001b[1;32m   1541\u001b[0m         \u001b[0;31m# maybe partial set\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1542\u001b[0m         \u001b[0mtake_split_path\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mobj\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_is_mixed_type\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1543\u001b[0;31m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1544\u001b[0m         \u001b[0;31m# if there is only one block/type, still have to take split path\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1545\u001b[0m         \u001b[0;31m# unless the block is one-dimensional or it can hold the value\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/pandas/core/indexing.py\u001b[0m in \u001b[0;36m_get_slice_axis\u001b[0;34m(self, slice_obj, axis)\u001b[0m\n\u001b[1;32m   1575\u001b[0m                     \u001b[0;31m# essentially this separates out the block that is needed\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1576\u001b[0m                     \u001b[0;31m# to possibly be modified\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1577\u001b[0;31m                     \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mndim\u001b[0m \u001b[0;34m>\u001b[0m \u001b[0;36m1\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0mi\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0minfo_axis\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1578\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1579\u001b[0m                         \u001b[0;31m# add the new item, and set the value\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/pandas/core/generic.py\u001b[0m in \u001b[0;36m_get_axis\u001b[0;34m(self, axis)\u001b[0m\n\u001b[1;32m    378\u001b[0m         \u001b[0maxis_number\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_get_axis_number\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0maxis\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    379\u001b[0m         \u001b[0;32massert\u001b[0m \u001b[0maxis_number\u001b[0m \u001b[0;32min\u001b[0m \u001b[0;34m{\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 380\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mindex\u001b[0m \u001b[0;32mif\u001b[0m \u001b[0maxis_number\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;36m0\u001b[0m \u001b[0;32melse\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcolumns\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    381\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    382\u001b[0m     \u001b[0;34m@\u001b[0m\u001b[0mclassmethod\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32mpandas/_libs/properties.pyx\u001b[0m in \u001b[0;36mpandas._libs.properties.AxisProperty.__get__\u001b[0;34m()\u001b[0m\n",
      "\u001b[0;31mTypeError\u001b[0m: descriptor 'axes' for 'BlockManager' objects doesn't apply to a 'BlockManager' object"
     ]
    }
   ],
   "source": [
    "train_metrics_df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "309ff92e-f9ae-4bb5-8dca-4509670618d1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
